# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param synth.incrementalSynthesisCache C:/Users/zhan4820/game_server_mar_22/lab_demo_2/.Xil/Vivado-4064-BA3145WS03/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.cache/wt [current_project]
set_property parent.project_path C:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/hdl/tcp_server_wrapper.v
add_files C:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/tcp_server.bd
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_microblaze_0_0/tcp_server_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_microblaze_0_0/tcp_server_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_microblaze_0_0/tcp_server_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_dlmb_v10_0/tcp_server_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_dlmb_v10_0/tcp_server_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ilmb_v10_0/tcp_server_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ilmb_v10_0/tcp_server_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_dlmb_bram_if_cntlr_0/tcp_server_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ilmb_bram_if_cntlr_0/tcp_server_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_lmb_bram_0/tcp_server_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_xbar_0/tcp_server_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_microblaze_0_axi_intc_0/tcp_server_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_microblaze_0_axi_intc_0/tcp_server_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_microblaze_0_axi_intc_0/tcp_server_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_mdm_1_0/tcp_server_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_mdm_1_0/tcp_server_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_clk_wiz_1_0/tcp_server_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_clk_wiz_1_0/tcp_server_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_clk_wiz_1_0/tcp_server_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_rst_clk_wiz_1_100M_0/tcp_server_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_rst_clk_wiz_1_100M_0/tcp_server_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_rst_clk_wiz_1_100M_0/tcp_server_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_ethernetlite_0_0/tcp_server_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_ethernetlite_0_0/tcp_server_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_ethernetlite_0_0/tcp_server_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_ethernetlite_0_0/tcp_server_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_mii_to_rmii_0_0/tcp_server_mii_to_rmii_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_mii_to_rmii_0_0/tcp_server_mii_to_rmii_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_timer_0_0/tcp_server_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_timer_0_0/tcp_server_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_mig_7series_0_0/tcp_server_mig_7series_0_0/user_design/constraints/tcp_server_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_mig_7series_0_0/tcp_server_mig_7series_0_0/user_design/constraints/tcp_server_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_mig_7series_0_0/tcp_server_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_uartlite_0_0/tcp_server_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_uartlite_0_0/tcp_server_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_uartlite_0_0/tcp_server_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_1/bd_d0ef_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_1/bd_d0ef_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_2/bd_d0ef_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_2/bd_d0ef_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_3/bd_d0ef_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_3/bd_d0ef_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_4/bd_d0ef_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_5/bd_d0ef_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_6/bd_d0ef_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_7/bd_d0ef_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_8/bd_d0ef_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_12/bd_d0ef_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_13/bd_d0ef_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_14/bd_d0ef_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_15/bd_d0ef_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_16/bd_d0ef_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_17/bd_d0ef_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_21/bd_d0ef_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_22/bd_d0ef_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_23/bd_d0ef_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_24/bd_d0ef_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_25/bd_d0ef_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_26/bd_d0ef_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_27/bd_d0ef_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_28/bd_d0ef_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_smc_0/bd_0/ip/ip_29/bd_d0ef_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_rst_mig_7series_0_81M_0/tcp_server_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_rst_mig_7series_0_81M_0/tcp_server_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_rst_mig_7series_0_81M_0/tcp_server_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ila_0_0/tcp_server_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_vio_0_0/tcp_server_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_vio_0_0/tcp_server_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_gpio_0_0/tcp_server_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_gpio_0_0/tcp_server_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_axi_gpio_0_0/tcp_server_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/tcp_server_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/constrs_1/new/eth_ref_clk.xdc
set_property used_in_implementation false [get_files C:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/constrs_1/new/eth_ref_clk.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top tcp_server_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tcp_server_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tcp_server_wrapper_utilization_synth.rpt -pb tcp_server_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
