# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ilmb_bram_if_cntlr_0/tcp_server_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'tcp_server_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ilmb_bram_if_cntlr_0/tcp_server_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tcp_server_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ilmb_bram_if_cntlr_0/tcp_server_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'tcp_server_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhan4820/game_server_mar_22/lab_demo_2/lab_demo_2.srcs/sources_1/bd/tcp_server/ip/tcp_server_ilmb_bram_if_cntlr_0/tcp_server_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tcp_server_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
