# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/chanmi53/snake_game_axi4_full_folder/snake_game_axi4_full/snake_game_axi4_full.cache/wt [current_project]
set_property parent.project_path C:/Users/chanmi53/snake_game_axi4_full_folder/snake_game_axi4_full/snake_game_axi4_full.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/chanmi53/snake_game_axi4_full_folder/final_demo_food_fix
  c:/Users/chanmi53/snake_game_axi4_full_folder/final_demo_snake_axi4_full
  c:/users/budiwarm/snake_game_axi4_full_folder/snake_game_2_player_mar27
  c:/users/budiwarm/snake_game_axi4_full_folder/snake_game_2_player_slvreg
  c:/Users/chanmi53/snake_game_axi4_full_folder/2player_snake_game_axi
  c:/Users/chanmi53/snake_game_axi4_full_folder/snake_game_slave_newaddr
  c:/Users/chanmi53/snake_game_axi4_full_folder/snake_game_slave_food2
  c:/Users/chanmi53/snake_game_axi4_full_folder/snake_game_slave_food
  c:/Users/chanmi53/snake_game_ip
  c:/Users/chanmi53/snake_game_axi4_full_folder/snake_game_slave_axi_folder/snake_game_slave_axi_ip
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/chanmi53/snake_game_axi4_full_folder/snake_game_axi4_full/snake_game_axi4_full.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv C:/Users/chanmi53/snake_game_files/snake_game_axi4_full.sv
read_ip -quiet C:/Users/chanmi53/snake_game_axi4_full_folder/snake_game_axi4_full/snake_game_axi4_full.srcs/sources_1/ip/snake_game_slave_axi_0/snake_game_slave_axi_0.xci

read_ip -quiet C:/Users/chanmi53/snake_game_axi4_full_folder/snake_game_axi4_full/snake_game_axi4_full.srcs/sources_1/ip/snake_game_top_0/snake_game_top_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top snake_game_axi4_full -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef snake_game_axi4_full.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file snake_game_axi4_full_utilization_synth.rpt -pb snake_game_axi4_full_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
