# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/chanmi53/VGA_mar_7_work/VGA/VGA.srcs/sources_1/bd/design_1/ip/design_1_snake_game_axi4_full_0_1/design_1_snake_game_axi4_full_0_1.xci
# IP: The module: 'design_1_snake_game_axi4_full_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/chanmi53/VGA_mar_7_work/VGA/VGA.srcs/sources_1/bd/design_1/ip/design_1_snake_game_axi4_full_0_1/src/snake_game_slave_axi_0/snake_game_slave_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_game_slave_axi_0 || ORIG_REF_NAME==snake_game_slave_axi_0} -quiet] -quiet

# IP: c:/Users/chanmi53/VGA_mar_7_work/VGA/VGA.srcs/sources_1/bd/design_1/ip/design_1_snake_game_axi4_full_0_1/src/snake_game_top_0/snake_game_top_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_game_top_0 || ORIG_REF_NAME==snake_game_top_0} -quiet] -quiet

# IP: c:/Users/chanmi53/VGA_mar_7_work/VGA/VGA.srcs/sources_1/bd/design_1/ip/design_1_snake_game_axi4_full_0_1/design_1_snake_game_axi4_full_0_1.xci
# IP: The module: 'design_1_snake_game_axi4_full_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/chanmi53/VGA_mar_7_work/VGA/VGA.srcs/sources_1/bd/design_1/ip/design_1_snake_game_axi4_full_0_1/src/snake_game_slave_axi_0/snake_game_slave_axi_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_game_slave_axi_0 || ORIG_REF_NAME==snake_game_slave_axi_0} -quiet] -quiet

# IP: c:/Users/chanmi53/VGA_mar_7_work/VGA/VGA.srcs/sources_1/bd/design_1/ip/design_1_snake_game_axi4_full_0_1/src/snake_game_top_0/snake_game_top_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_game_top_0 || ORIG_REF_NAME==snake_game_top_0} -quiet] -quiet
